### ISSUE TITLE
Enter "Keywords" in one line

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#108]
Allowing enter ‘Keywords’ in ‘Record information’ in one line, separated by commas.

**Comment by MadCatX** [comment]
This would require an introduction of a new component, an `ImpliedArray`. Internal data would be stored as string and converted to/from array upon store/load from MBDB. Implementation should be straightforward.

A few things that should be considered:
- When would we use `ImpliedArray` instead of the current element-based array? Would we use it for all "simple" data or only in hand-picked cases?
- Would we want to use delimiters other than comma?
- Would we want to allow input such as `"first element" "second element" third fourth`?

**Comment by edager** [comment]
In order to simplify the schema the keywords will be removed, especially as they're not qualified nor do they link to ontologies so they hamper interoperability. It will be removed in general parameters 0.9.17
