### ISSUE TITLE
Search behaviour - partial match of word 

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#58]
It may be a current feature but searching for a partial word 
SCV 
(SCV50) is present in the inhibitor name
gave nothing
so I had to search for SCV50 to find the records ..

**Comment by edager** [comment]
It turns out that this is actually rather difficult to fix.  As it will require a adding extensive mapping information to each of the fields where this is needed i.e. there's isn't a reasonable way of changing the search configuration in general to accomplish this. It will have to be done eventually though
